### ISSUE TITLE
add support to sending attributes

### ISSUE THREAD

**Issue by javamonkey79** [newrelic/newrelic-java-log4j-appender#3]
## Summary

We need to be able to send [Attributes](https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/ae5f90d6f867bec96ef4ec3756d66f071d24dcd2/telemetry-core/src/main/java/com/newrelic/telemetry/Attributes.java), in order to use this, to isolate which environment we're sending to.

## Desired Behavior

The appender could be configured to accept attribute values in the XML.

## Possible Solution

Change NewRelicBatchingAppender to accept a map of attributes.

## Additional context

Without this ability, we can't use this plugin.

**Comment by gsidhwani-nr** [comment]
I have released v1.0.2 with support of  custom fields - Comma separated Name=Value String pairs. Please test and let me know.
